version: '3.8'

services:
  backend-bank-api:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
#      - SPRING_DRIVER_CLASS_NAME=
#      - SPRING_DATASOURCE_URL=
#      - SPRING_DATASOURCE_USERNAME=
#      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_DRIVER_CLASS_NAME=org.h2.Driver
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:bankdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      - SPRING_DATASOURCE_USERNAME=SA
      - SPRING_DATASOURCE_PASSWORD=
      - MS_BANK_URL=http://backend-bank-api:8080
    networks:
      - shared_network

networks:
  shared_network:
