version: '3.8'

services:
  backend-bank-api:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DRIVER_CLASS_NAME=
      - SPRING_DATASOURCE_URL=
      - SPRING_DATASOURCE_USERNAME=
      - SPRING_DATASOURCE_PASSWORD=
      - MS_BANK_URL=http://backend-bank-api:8080
    networks:
      - shared_network

networks:
  shared_network:
    driver: bridge
    external: true
