global:
  scrape_interval: 5s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'bank_api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['backend-bank-api:8080']
